version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10 # need this for adx installation

    commands:
      - npm i -g yarn
      - yum install wget

      # Install SFDX (https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux)
      - wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      - mkdir sfdx
      - tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
      - ./sfdx/install

      # Install ADX
      - yarn global add @appirio/dx
  build:
    commands:
      - adx --version
      - sdx --version
