version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10 # need this for adx installation

    commands:
      - npm i -g yarn

      # Install SFDX CLI
      - yarn global add sfdx-cli
  build:
    commands:
      - adx --version
      - sdx --version
