version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10 # need this for adx installation

    commands:
      # Install SFDX CLI
      - yarn global add sfdx-cli @appirio/salesforce
  build:
    commands:
      - sfdx --version
      - adx --version
