version: 0.2

env:
  variables:
    ADX_DIR: adx-cli

phases:
  install:
    runtime-versions:
      nodejs: 10

    commands:
      # Install SFDX CLI
      - yarn global add sfdx-cli

      # Install ADX
      - yum install -y gcc-c++ # ADX requires a few different versions of glibc
      - wget https://dx.appirio.com/downloads/adx-cli-linux.tar.gz -P ${ADX_DIR}
      - (cd ${ADX_DIR} && tar -xzf adx-cli-linux.tar.gz)
      - export PATH=$(pwd)/${ADX_DIR}:$PATH

  build:
    commands:
      - sfdx --version
      - adx --version
